import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/coverage/**",
      ".husky/**",
      "pnpm-lock.yaml",
      // Generated by Next.js; its triple-slash references are not ours to style.
      "**/next-env.d.ts",
    ],
  },
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
);
