import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

import { factoryPlugin } from "./eslint.factory-rules.mjs";

// ---------------------------------------------------------------------------------------
// "factory" plugin wiring (design spec §8.4, plan D.5 + D.9.3): the two enforcement rules
// that make the safe way the only way that compiles and lints —
//   - factory/no-raw-handler — kills raw Next.js route handlers and raw "use server"
//     exports. The only legal way to export an HTTP method from a route file, or a value
//     from a "use server" file, is a direct `defineHandler(...)` / `defineAction(...)`
//     call (or the one documented framework-mount exception).
//   - factory/no-process-env — kills direct `process.env` reads outside the handful of
//     files that are explicitly allowed to own env parsing.
//
// The rules themselves (and their shared helpers) live in the sibling
// `eslint.factory-rules.mjs` module — extracted so they can be driven directly by
// `packages/config/test/factory-eslint-rules.test.ts` via ESLint's `Linter`, independent
// of this flat config's file-glob wiring. This file only wires that plugin's rules to the
// paths they apply to.
// ---------------------------------------------------------------------------------------

// Every registered env var name is expected to route through packages/config. These are
// the ONLY places allowed to touch `process.env` directly (plan D.5/D.9):
//   - packages/config/src/**      the registry's own zod parse + merged-env primitives
//   - packages/config/scripts/**  doctor's own env read (mirrors src's merge logic)
//   - packages/db/scripts/**      migrate.ts/seed.ts — argv/exit-code checks, and any
//                                 direct env reads there are pre-readMergedEnv bootstrap
//   - packages/create/src/**      the installer CLI (bundled/published standalone — can't
//                                 import @factory/config, see dag-create-imports-no-
//                                 workspace-package); FABULOUS_FACTORY_TEMPLATES_DIR is a
//                                 test-only override (npx-installer design spec §6)
//   - **/test/**, **/*.test.*     test code builds its own env/DB fixtures
//   - **/vitest.config.*          test runner config, not app/script code
//   - **/next.config.*            build-time Next config, not app/script code
//   - .dependency-cruiser.cjs     boundary-tool config, not app/script code
const PROCESS_ENV_EXCEPTIONS = [
  "packages/config/src/**",
  "packages/config/scripts/**",
  "packages/db/scripts/**",
  "packages/create/src/**",
  "**/test/**",
  "**/*.test.*",
  "**/vitest.config.*",
  "**/next.config.*",
  ".dependency-cruiser.cjs",
];

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/coverage/**",
      ".husky/**",
      "pnpm-lock.yaml",
      // Generated by Next.js; its triple-slash references are not ours to style.
      "**/next-env.d.ts",
      // Ephemeral compose output (npx-installer design spec §5) — generated by `pnpm
      // compose`/`prepack`, never committed. Linting it would both waste time re-checking
      // verbatim copies of already-linted source and re-run the raw-handler/process-env
      // rules against nested `packages/*` copies whose paths no longer match this
      // config's app-rooted regexes.
      "packages/create/templates/**",
      // tsup's bundled build output — generated, not ours to style.
      "packages/create/dist/**",
    ],
  },
  ...tseslint.configs.recommended,
  eslintConfigPrettier,

  // Raw-handler ban: scoped to source under apps/ and packages/ (route files live under
  // apps/*/app/**; "use server" files could live anywhere in app or package source, and
  // the directive check inside the rule is what actually decides whether it applies).
  {
    // Every JS/TS extension Next.js accepts for a route handler, and every extension a
    // "use server" file could plausibly use — not just `.ts`/`.tsx` (D.9 bypass fix:
    // `route.js`/`route.mjs` used to escape the rule entirely because ESLint never even
    // ran it against those files).
    files: [
      "apps/**/*.ts",
      "apps/**/*.tsx",
      "apps/**/*.js",
      "apps/**/*.jsx",
      "apps/**/*.mjs",
      "apps/**/*.cjs",
      "apps/**/*.mts",
      "apps/**/*.cts",
      "packages/**/*.ts",
      "packages/**/*.tsx",
      "packages/**/*.js",
      "packages/**/*.jsx",
      "packages/**/*.mjs",
      "packages/**/*.cjs",
      "packages/**/*.mts",
      "packages/**/*.cts",
    ],
    plugins: { factory: factoryPlugin },
    rules: {
      "factory/no-raw-handler": "error",
    },
  },

  // process.env ban: everywhere, minus the documented exceptions below.
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts", "**/*.mjs", "**/*.cjs"],
    plugins: { factory: factoryPlugin },
    rules: {
      "factory/no-process-env": "error",
    },
  },
  {
    files: PROCESS_ENV_EXCEPTIONS,
    plugins: { factory: factoryPlugin },
    rules: {
      "factory/no-process-env": "off",
    },
  },
);
