#!/usr/bin/env node
/**
 * Generates the root `.env.example` from `ENV_REGISTRY` — deterministic, grouped by
 * `ServiceGroup`, each var preceded by its description comment. Required vars are
 * uncommented with their example value; optional vars are commented out.
 *
 * `--check` re-generates in memory and exits 1 with a diff hint if the file on disk
 * differs (CI staleness gate — spec §8.1 "the two can never disagree").
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { ENV_REGISTRY, type EnvVarSpec, type ServiceGroup } from "../src/registry";

const GROUP_ORDER: readonly ServiceGroup[] = [
  "core",
  "billing",
  "llm",
  "email",
  "jobs",
  "analytics",
  "observability",
];

const GROUP_TITLES: Record<ServiceGroup, string> = {
  core: "Core",
  billing: "Billing (Stripe)",
  llm: "LLM gateway",
  email: "Email",
  jobs: "Jobs (Inngest)",
  analytics: "Analytics (PostHog)",
  observability: "Observability (Sentry)",
};

function formatVar(spec: EnvVarSpec): string {
  const comment = `# ${spec.description}`;
  const line = `${spec.name}=${spec.example ?? ""}`;
  return spec.required ? `${comment}\n${line}` : `${comment}\n# ${line}`;
}

/** Pure — exported for tests. Deterministic: same registry always produces the same string. */
export function generateEnvExample(): string {
  const header = [
    "# Fabulous Factory — environment variables",
    "# Generated by packages/config/scripts/gen-env-example.ts — do not edit by hand.",
    "# Run 'pnpm gen:env-example' to regenerate.",
    "#",
    "# Only DATABASE_URL is required. Everything else is optional — the app boots with",
    "# nothing else set, and each service lights up progressively as you fill in its vars.",
  ].join("\n");

  const sections = GROUP_ORDER.map((group) => {
    const vars = ENV_REGISTRY.filter((spec) => spec.group === group);
    if (vars.length === 0) return null;
    const body = vars.map(formatVar).join("\n\n");
    return `# ---- ${GROUP_TITLES[group]} ----\n${body}`;
  }).filter((section): section is string => section !== null);

  return `${header}\n\n${sections.join("\n\n")}\n`;
}

/** Pure — exported for tests. True when `diskContent` matches the current generated output. */
export function isEnvExampleUpToDate(diskContent: string): boolean {
  return diskContent === generateEnvExample();
}

const __filename = fileURLToPath(import.meta.url);
const invokedDirectly =
  process.argv[1] !== undefined && path.resolve(process.argv[1]) === path.resolve(__filename);

if (invokedDirectly) {
  const repoRoot = path.resolve(path.dirname(__filename), "../../..");
  const outputPath = path.join(repoRoot, ".env.example");
  const content = generateEnvExample();
  const checkMode = process.argv.includes("--check");

  if (checkMode) {
    const existing = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
    if (!isEnvExampleUpToDate(existing)) {
      console.error(".env.example is out of date with packages/config/src/registry.ts.");
      console.error("Run 'pnpm gen:env-example' to regenerate it, then commit the result.");
      process.exit(1);
    }
    console.log(".env.example is up to date.");
  } else {
    writeFileSync(outputPath, content, "utf8");
    console.log(`Wrote ${outputPath}`);
  }
}
