import type { ReactElement } from "react";

import { render } from "@react-email/render";
import { describe, expect, it } from "vitest";

import { TEMPLATES, type TemplateName, type TemplateProps } from "../src/templates";

const PROPS: { [K in TemplateName]: TemplateProps[K] } = {
  "verify-email": { url: "https://example.com/verify?token=abc" },
  "magic-link": { url: "https://example.com/magic?token=xyz" },
  "change-digest": {
    monitorName: "Pricing page",
    url: "https://example.com/pricing",
    summary: "The plan price changed from $10 to $12.",
    source: "diff",
  },
};

// Indexing TEMPLATES/PROPS by the widened `TemplateName` union `describe.each` hands the
// callback below doesn't type-check directly (TS can't correlate which union member each
// call uses); a small generic helper — indexed by its own type param `K`, not the outer
// union — restores the per-key correlation.
function renderElement<K extends TemplateName>(name: K): ReactElement {
  return TEMPLATES[name](PROPS[name]);
}

describe.each(Object.keys(TEMPLATES) as TemplateName[])("templates — %s", (name) => {
  it("renders without throwing and produces both an html and a text version", async () => {
    const element = renderElement(name);

    const html = await render(element);
    const text = await render(element, { plainText: true });

    expect(typeof html).toBe("string");
    expect(html).toContain("<html");
    expect(html).toContain(PROPS[name].url);

    expect(typeof text).toBe("string");
    expect(text.length).toBeGreaterThan(0);
    expect(text).toContain(PROPS[name].url);
  });
});

describe("templates — change-digest", () => {
  const props = PROPS["change-digest"];

  it("renders monitor name, url, and summary in both html and text", async () => {
    const element = TEMPLATES["change-digest"](props);

    const html = await render(element);
    const text = await render(element, { plainText: true });

    for (const value of [props.monitorName, props.url, props.summary]) {
      expect(html).toContain(value);
      expect(text).toContain(value);
    }
  });

  it("discloses AI generation only when source is 'llm'", async () => {
    const llmHtml = await render(TEMPLATES["change-digest"]({ ...props, source: "llm" }));
    const diffHtml = await render(TEMPLATES["change-digest"]({ ...props, source: "diff" }));

    expect(llmHtml.toLowerCase()).toContain("generated by ai");
    expect(diffHtml.toLowerCase()).not.toContain("generated by ai");
  });
});
