#!/usr/bin/env tsx
/**
 * Runs pending Drizzle migrations against `DATABASE_URL`.
 *
 * Builds its own `Pool` here — never imports `../src/index.ts`, whose first line is
 * `import "server-only"` (that poison throws outside the `react-server` condition and
 * would kill this script under plain `tsx`).
 *
 * Multi-chain layout (preset domains don't ship each other's tables): the SHARED chain
 * lives at `../migrations` (this package, default journal table `__drizzle_migrations`),
 * run first. Each DOMAIN chain lives at an immediate subdirectory of that folder (e.g.
 * `../migrations/untangle/`, `../migrations/brainstorm/`) with its own
 * `meta/_journal.json`, generated by the owning package's own `drizzle-kit generate` —
 * this script only discovers and runs them, never generates them. Zero, one, or many
 * domain chains may exist at once; this script must handle all three (a scaffold that
 * only kept `packages/db` and no domain package has zero). Each domain chain runs with
 * `migrationsTable: "__drizzle_migrations_<dirname>"` so its history never collides with
 * the shared chain's or another domain's in the `drizzle` schema.
 *
 * Two modes:
 *   - plain (default): used by `pnpm db:migrate` and CI. Hard-fails (non-zero exit) on
 *     any error — missing `DATABASE_URL`, unreachable DB, or a migration error.
 *   - `--predev`: used by `apps/web`'s `dev` script ahead of `next dev`. ALWAYS exits 0,
 *     so `pnpm dev` never fails to start:
 *       - `FACTORY_SKIP_MIGRATIONS=1` → skip entirely, print why.
 *       - `DATABASE_URL` missing/unset → warn with a hint, continue without migrating.
 *       - DB unreachable → warn with a hint (e.g. "is Postgres running?"), continue.
 *       - DB reachable → run pending migrations normally.
 *
 * 2026-08-22 pre-1.0 squash: the shared chain's seven-entry history (0000_mixed_ogun …
 * 0006_cynical_black_bolt) was squashed into a single new baseline
 * (`0000_cool_edwin_jarvis.sql`), and the untangle/brainstorm tables that used to live in
 * that chain were split into their own domain chains alongside it. This is a deliberate,
 * irreversible history rewrite, safe pre-1.0 because nothing has shipped to an adopter
 * yet — verified statement-by-statement to add or drop nothing relative to the old chain
 * (net state is identical). It is NOT safe to layer on top of a database already migrated
 * through the old chain: Drizzle reapplies any migration newer than the last applied
 * `folderMillis`, so the new baseline's `CREATE TABLE`s collide with the old chain's
 * already-created tables. Any pre-existing dev database must be dropped and recreated
 * (`pnpm db:migrate` against a fresh database), or hand-stamped by inserting a row into
 * `drizzle.__drizzle_migrations` (and `__drizzle_migrations_<domain>` for each domain
 * chain) recording the new baseline as already applied. A freshly scaffolded project
 * always starts from an empty database and is unaffected.
 */
import { readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { readMergedEnv } from "@factory/config/node";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Resolved relative to this file, NOT `process.cwd()` — `pnpm db:migrate` and the
// `apps/web` predev hook both invoke this script via `tsx` from different working
// directories, so a cwd-relative path would be fragile.
const MIGRATIONS_FOLDER = path.resolve(__dirname, "../migrations");

const isPredev = process.argv.includes("--predev");

/**
 * Postgres truncates identifiers at 63 bytes. `__drizzle_migrations_` is 21 of those, so
 * two domain directory names sharing their first (63 - 21) = 42 characters would collide
 * onto the same journal table and cross-apply each other's history. This caps well below
 * that so the collision can never be reached in practice.
 */
const MAX_DOMAIN_NAME_LENGTH = 40;

/**
 * Immediate subdirectories of `MIGRATIONS_FOLDER` that look like a Drizzle migration
 * chain (have their own `meta/_journal.json`), sorted alphabetically for a stable,
 * deterministic run order. SHALLOW — one level only, never recurses.
 *
 * Exported for `packages/db/test/migrate-discovery.test.ts` — this is real branching
 * logic (ordering, the `meta/` non-chain exclusion, the zero/one/many contract) and
 * deserves direct unit coverage, not just the CI end-to-end.
 */
export function discoverDomainChains(migrationsFolder: string): string[] {
  if (!existsSync(migrationsFolder)) {
    return [];
  }
  const domains = readdirSync(migrationsFolder, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => existsSync(path.join(migrationsFolder, name, "meta", "_journal.json")))
    .sort();
  for (const domain of domains) {
    if (domain.length > MAX_DOMAIN_NAME_LENGTH) {
      throw new Error(
        `[db:migrate] Domain migration chain "${domain}" is longer than ` +
          `${MAX_DOMAIN_NAME_LENGTH} characters — its journal table name ` +
          `("__drizzle_migrations_${domain}") risks Postgres's 63-byte identifier ` +
          "truncation colliding with another domain's. Rename the directory.",
      );
    }
  }
  return domains;
}

async function runMigrations(connectionString: string): Promise<void> {
  const pool = new Pool({ connectionString });
  try {
    const db = drizzle({ client: pool });

    console.log(`[db:migrate] Running shared chain (${MIGRATIONS_FOLDER})...`);
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });

    const domains = discoverDomainChains(MIGRATIONS_FOLDER);
    if (domains.length === 0) {
      console.log("[db:migrate] no domain migration chains found.");
      return;
    }
    for (const domain of domains) {
      const migrationsFolder = path.join(MIGRATIONS_FOLDER, domain);
      const migrationsTable = `__drizzle_migrations_${domain}`;
      console.log(
        `[db:migrate] Running domain chain "${domain}" (${migrationsFolder}, table ${migrationsTable})...`,
      );
      await migrate(db, { migrationsFolder, migrationsTable });
    }
  } finally {
    await pool.end();
  }
}

async function main(): Promise<void> {
  // Read the registered vars through the shared merged view (.env merged under the real
  // environment) so FACTORY_SKIP_MIGRATIONS works from the .env file too, like every
  // other registered variable.
  const env = readMergedEnv();

  if (isPredev && env.FACTORY_SKIP_MIGRATIONS === "1") {
    console.log("[db:migrate] FACTORY_SKIP_MIGRATIONS=1 — skipping predev migrations.");
    return;
  }

  const connectionString = env.DATABASE_URL;

  if (!connectionString) {
    const message =
      "[db:migrate] DATABASE_URL is not set — see .env.example. Set it in your environment or .env file.";
    if (isPredev) {
      console.warn(`${message} Continuing without running migrations.`);
      return;
    }
    throw new Error(message);
  }

  try {
    console.log("[db:migrate] Running pending migrations...");
    await runMigrations(connectionString);
    console.log("[db:migrate] Done.");
  } catch (error) {
    if (isPredev) {
      console.warn(
        "[db:migrate] Could not run migrations — is Postgres running and DATABASE_URL correct?",
      );
      console.warn(`[db:migrate] ${error instanceof Error ? error.message : String(error)}`);
      console.warn("[db:migrate] Continuing to start `pnpm dev` anyway.");
      return;
    }
    throw error;
  }
}

// Gated the same way `packages/config/scripts/gen.ts` gates its own CLI entry point:
// `main()` must not run as a side effect of a test importing `discoverDomainChains` above.
const invokedDirectly =
  process.argv[1] !== undefined && path.resolve(process.argv[1]) === path.resolve(__filename);

if (invokedDirectly) {
  main()
    .then(() => {
      // --predev always exits 0, even on a handled warning path above (no throw reaches
      // here in that case). Plain mode reaching here means success too.
      process.exitCode = 0;
    })
    .catch((error) => {
      console.error("[db:migrate] Migration failed:");
      console.error(error);
      // Plain mode: hard-fail. --predev mode: every failure path above is caught and
      // returns normally, so this catch only fires for a truly unexpected throw — still
      // exit 0 to honor the "pnpm dev always starts" contract.
      process.exitCode = isPredev ? 0 : 1;
    });
}
