/**
 * Minimal hand-authored JSX (plan E.2/E.9) — plain html/body/a, no components library.
 * See `verify-email.tsx` for why `react-email`/`@react-email/components` aren't a dep.
 *
 * Sent by the demo monitor pipeline (plan G.2.5/G.5) when `checkMonitor` detects a
 * change. `summary` is either an LLM-generated digest or a `diffLines` excerpt fallback —
 * `source` tells the recipient which, so an AI-generated summary is always labeled as such.
 */
export interface ChangeDigestProps {
  /** The user-facing name of the monitor that detected the change. */
  monitorName: string;
  /** The monitored URL. */
  url: string;
  /** The change summary — LLM-generated or a diff excerpt, capped at 500 chars (G.10.7). */
  summary: string;
  /** Which pipeline produced `summary` — drives the AI-generated disclosure below. */
  source: "llm" | "diff";
}

export function ChangeDigestTemplate({ monitorName, url, summary, source }: ChangeDigestProps) {
  return (
    <html>
      <body>
        <p>
          A change was detected on <strong>{monitorName}</strong>:
        </p>
        <p>
          <a href={url}>{url}</a>
        </p>
        <p>{summary}</p>
        {source === "llm" ? <p>This summary was generated by AI.</p> : null}
      </body>
    </html>
  );
}
